PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX tm:  <http://www.example.org/turing-machine#> 

SELECT * WHERE { ?tapePosition rdf:first ?tapeValueAtPosition ; rdf:rest ?nextTapePosition . }
